name: test

on: 
  push:
  workflow_dispatch:

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        uses: dagger/dagger-for-github@v3
        with:
          cmds: 
            do test